server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/carefree_health_test?serverTimeZone=UTC&characterEncoding=UTF-8&useSSL=false
    hikari:
      username: health_admin
      password: Health_admin1234!!
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /carefree-api-docs
    enabled: true
  swagger-ui:
    path: /carefree-swagger-ui.html
    enabled: true
    groups-order: asc
    tags-sorter: alpha # alphabet 순 tag 정렬
    operations-sorter: alpha # alphabet 순 tag 정렬
    display-request-duration: true # API 호출 소요 시간 노출
    disable-swagger-default-url: true
  cache:
    disabled: true